PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS llm_settings (
  id TEXT PRIMARY KEY CHECK (id = 'default'),
  llm_server_path TEXT NOT NULL,
  llm_gguf_path TEXT,
  llm_mmproj_path TEXT,
  llm_server_url TEXT NOT NULL,
  llm_host TEXT NOT NULL,
  llm_port INTEGER NOT NULL,
  llm_n_ctx INTEGER NOT NULL,
  llm_n_threads INTEGER,
  llm_n_gpu_layers INTEGER,
  llm_n_batch INTEGER,
  llm_n_parallel INTEGER,
  llm_seed INTEGER,
  llm_rope_freq_base REAL,
  llm_rope_freq_scale REAL,
  llm_use_jinja INTEGER NOT NULL CHECK (llm_use_jinja IN (0, 1)),
  llm_cache_prompt INTEGER NOT NULL CHECK (llm_cache_prompt IN (0, 1)),
  llm_flash_attn INTEGER NOT NULL CHECK (llm_flash_attn IN (0, 1)),
  max_tokens INTEGER NOT NULL,
  temperature REAL NOT NULL,
  top_p REAL,
  top_k INTEGER,
  repeat_penalty REAL,
  request_seed INTEGER,
  use_fake_reply INTEGER NOT NULL CHECK (use_fake_reply IN (0, 1)),
  fake_reply_text TEXT
);

INSERT OR IGNORE INTO llm_settings (
  id,
  llm_server_path,
  llm_gguf_path,
  llm_mmproj_path,
  llm_server_url,
  llm_host,
  llm_port,
  llm_n_ctx,
  llm_n_threads,
  llm_n_gpu_layers,
  llm_n_batch,
  llm_n_parallel,
  llm_seed,
  llm_rope_freq_base,
  llm_rope_freq_scale,
  llm_use_jinja,
  llm_cache_prompt,
  llm_flash_attn,
  max_tokens,
  temperature,
  top_p,
  top_k,
  repeat_penalty,
  request_seed,
  use_fake_reply,
  fake_reply_text
) VALUES (
  'default',
  '__unset_llm_server__',
  NULL,
  NULL,
  'http://127.0.0.1:8080/v1/chat/completions',
  '127.0.0.1',
  8080,
  4096,
  NULL,
  99,
  NULL,
  4,
  NULL,
  NULL,
  NULL,
  1,
  1,
  1,
  1024,
  0.2,
  0.95,
  40,
  1.1,
  NULL,
  1,
  'LLM is not configured yet. This is a fake response.'
);
