PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS llm_selection_defaults (
  model_key TEXT PRIMARY KEY,
  display_name TEXT NOT NULL,
  hf_repo_id TEXT NOT NULL,
  hf_filename TEXT NOT NULL,
  mmproj_filename TEXT,
  backend TEXT NOT NULL,
  model_family TEXT NOT NULL,
  llm_server_path TEXT NOT NULL,
  llm_gguf_path TEXT,
  llm_mmproj_path TEXT,
  llm_server_url TEXT NOT NULL,
  llm_host TEXT NOT NULL,
  llm_port INTEGER NOT NULL,
  llm_n_ctx INTEGER NOT NULL,
  llm_n_threads INTEGER,
  llm_n_gpu_layers INTEGER,
  llm_n_batch INTEGER,
  llm_n_parallel INTEGER,
  llm_seed INTEGER,
  llm_rope_freq_base REAL,
  llm_rope_freq_scale REAL,
  llm_use_jinja INTEGER NOT NULL CHECK (llm_use_jinja IN (0, 1)),
  llm_cache_prompt INTEGER NOT NULL CHECK (llm_cache_prompt IN (0, 1)),
  llm_flash_attn INTEGER NOT NULL CHECK (llm_flash_attn IN (0, 1)),
  max_tokens INTEGER NOT NULL,
  temperature REAL NOT NULL,
  top_p REAL,
  top_k INTEGER,
  repeat_penalty REAL,
  request_seed INTEGER,
  use_fake_reply INTEGER NOT NULL CHECK (use_fake_reply IN (0, 1)),
  fake_reply_text TEXT,
  CHECK (backend IN ('server'))
);

CREATE TABLE IF NOT EXISTS llm_selection (
  model_key TEXT PRIMARY KEY,
  display_name TEXT NOT NULL,
  local_gguf_path TEXT NOT NULL,
  local_mmproj_path TEXT,
  downloaded_at TEXT NOT NULL,
  is_active INTEGER NOT NULL DEFAULT 0 CHECK (is_active IN (0, 1)),
  FOREIGN KEY (model_key) REFERENCES llm_selection_defaults(model_key) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_llm_selection_single_active
ON llm_selection (is_active)
WHERE is_active = 1;

CREATE INDEX IF NOT EXISTS idx_llm_selection_downloaded_at
ON llm_selection (downloaded_at);

INSERT OR IGNORE INTO llm_selection_defaults (
  model_key,
  display_name,
  hf_repo_id,
  hf_filename,
  mmproj_filename,
  backend,
  model_family,
  llm_server_path,
  llm_gguf_path,
  llm_mmproj_path,
  llm_server_url,
  llm_host,
  llm_port,
  llm_n_ctx,
  llm_n_threads,
  llm_n_gpu_layers,
  llm_n_batch,
  llm_n_parallel,
  llm_seed,
  llm_rope_freq_base,
  llm_rope_freq_scale,
  llm_use_jinja,
  llm_cache_prompt,
  llm_flash_attn,
  max_tokens,
  temperature,
  top_p,
  top_k,
  repeat_penalty,
  request_seed,
  use_fake_reply,
  fake_reply_text
) VALUES (
  'qwen3_4b_q8',
  'Qwen3 4B Q8_0',
  'Qwen/Qwen3-4B-GGUF',
  'Qwen3-4B-Q8_0.gguf',
  NULL,
  'server',
  'instruct/think',
  '__unset_llm_server__',
  NULL,
  NULL,
  'http://127.0.0.1:8080/v1/chat/completions',
  '127.0.0.1',
  8080,
  4096,
  NULL,
  99,
  NULL,
  4,
  NULL,
  NULL,
  NULL,
  1,
  1,
  1,
  1024,
  0.2,
  0.95,
  40,
  1.1,
  NULL,
  0,
  NULL
);

INSERT OR IGNORE INTO llm_selection_defaults (
  model_key,
  display_name,
  hf_repo_id,
  hf_filename,
  mmproj_filename,
  backend,
  model_family,
  llm_server_path,
  llm_gguf_path,
  llm_mmproj_path,
  llm_server_url,
  llm_host,
  llm_port,
  llm_n_ctx,
  llm_n_threads,
  llm_n_gpu_layers,
  llm_n_batch,
  llm_n_parallel,
  llm_seed,
  llm_rope_freq_base,
  llm_rope_freq_scale,
  llm_use_jinja,
  llm_cache_prompt,
  llm_flash_attn,
  max_tokens,
  temperature,
  top_p,
  top_k,
  repeat_penalty,
  request_seed,
  use_fake_reply,
  fake_reply_text
) VALUES (
  'qwen3_8b_q8',
  'Qwen3 8B Q8_0',
  'Qwen/Qwen3-8B-GGUF',
  'Qwen3-8B-Q8_0.gguf',
  NULL,
  'server',
  'instruct/think',
  '__unset_llm_server__',
  NULL,
  NULL,
  'http://127.0.0.1:8080/v1/chat/completions',
  '127.0.0.1',
  8080,
  8192,
  NULL,
  99,
  NULL,
  2,
  NULL,
  NULL,
  NULL,
  1,
  1,
  1,
  1024,
  0.15,
  0.9,
  50,
  1.05,
  NULL,
  0,
  NULL
);
